### ISSUE TITLE
bounds not taken into account

### ISSUE THREAD

**Issue by hugolarzabal** [dirkschumacher/ROI.plugin.cbc#6]
Hi Dirk,

I have noticed that any special bounds added with *set_bounds* in ompr are not taken into account when using cbc solver.

After looking into the code, I have noticed that default bounds are set at 0 and inf or 1 depending on the variable types. 
However there is nothing to translate the special bounds from ROI to Cbc. So any bounds stocked in *bounds$lower$val* or *bounds$upper$val* in ROI are replaced by the default bounds.

**Comment by hugolarzabal** [comment]
I have looked again into this issue today and I am making a PR to fix this problem.

**Comment by dirkschumacher** [comment]
Thanks. Odd, that there wasn't a test for it. Will look into it.

**Comment by dirkschumacher** [comment]
Fixed now. Thanks
